#Hugo configuration
title = "jh"
baseURL = "https:\/\/www.lol.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758397"
subfolder = ""
